extends: '.eslintrc.base.yml'
rules:
  fp/no-class: 0
overrides:
  - files: ['examples/plugin/*.ts']
    parserOptions:
      project: examples/plugin/tsconfig.json
    rules:
      # Plugin examples comment most of the code
      '@typescript-eslint/no-unused-vars': 0

  # CLI
  - files:
      [
        'src/bin/**/*.{js,cjs,mjs,ts,cts,mts}',
        'src/bin.{js,cjs,mjs,ts,cts,mts}',
      ]
    rules:
      # CLI often prints to console
      no-console: 0
      no-restricted-globals:
        - 2
        - global
        - GLOBAL
        - exports
        - process
        - Buffer
      # CLI often forwards to main commands using `import * as commands`
      import/no-namespace: 0

  # Benchmark files
  - files: ['benchmark/**/*.{js,cjs,mjs,ts,cts,mts}']
    rules:
      # Often used to signify number of iterations
      filenames/no-index: 0

      # Self imports
      import/no-unresolved: 0
      n/no-missing-import: 0
      n/no-extraneous-import: 0

  - files: ['benchmark/**/*.{js,cjs,mjs}']
    rules:
      # Often used to signify number of iterations
      no-magic-numbers: 0

      # Unused expressions are useful in benchmarks
      no-unused-expressions: 0

  - files: ['benchmark/**/*.{ts,cts,mts}']
    rules:
      '@typescript-eslint/no-magic-numbers': 0
      '@typescript-eslint/no-unused-expressions': 0

  # Type tests
  - files: ['**/*.test-d.ts']
    rules:
      # Unused expressions and arguments are useful in type tests
      no-new: 0
      '@typescript-eslint/no-unused-expressions': 0
      '@typescript-eslint/no-unused-vars':
        - 2
        - args: none

      # Unusual functions or methods or are useful in type tests
      'class-methods-use-this': 0
      '@typescript-eslint/no-useless-constructor': 0
      '@typescript-eslint/no-empty-function': 0

      # `test-d` is dasherized, but rest must use underscores
      filenames/match-regex:
        - 2
        - ^[a-zA-Z_][a-zA-Z0-9_.]+\.test-d$
      unicorn/filename-case:
        - 2
        - case: snakeCase
          ignore:
            - ^[a-zA-Z_][a-zA-Z0-9_.]+\.test-d\.ts$

      # Passing `undefined` is handled differently than passing no argument by
      # TypeScript, which can be tested
      unicorn/no-useless-undefined: 0
