extends: '@ehmicky/eslint-config/.eslintrc.yml'
rules:
  fp/no-class: 0
overrides:
  - files: ['examples/plugin/*.ts']
    parserOptions:
      project: examples/plugin/tsconfig.json
    rules:
      # Plugin examples comment most of the code
      '@typescript-eslint/no-unused-vars': 0

  - files: ['**/*.{ts,cts,mts}']
    rules:
      '@typescript-eslint/ban-ts-comment': 2
      '@typescript-eslint/prefer-ts-expect-error': 2
      '@typescript-eslint/ban-tslint-comment': 2
      # Enforce declaring types of parameters.
      # Use type inference otherwise, including for callbacks (arrow functions).
      '@typescript-eslint/typedef':
        - 2
        - parameter: true
          propertyDeclaration: true

  - files: ['**/*.test-d.ts']
    rules:
      '@typescript-eslint/ban-ts-comment':
        - 2
        - ts-expect-error: 0
