extends: '@ehmicky/eslint-config/.eslintrc.yml'
rules:
  fp/no-class: 0
overrides:
  - files: ['examples/plugin/*.ts']
    parserOptions:
      project: examples/plugin/tsconfig.json
    rules:
      # Plugin examples comment most of the code
      '@typescript-eslint/no-unused-vars': 0

  - files: ['**/*.{ts,cts,mts}']
    rules:
      '@typescript-eslint/ban-ts-comment': 2

  - files: ['**/*.test-d.ts']
    rules:
      '@typescript-eslint/ban-ts-comment':
        - 2
        - ts-expect-error: 0
